# Generated by Django 3.2.21 on 2024-02-03 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blindspot_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Name', models.CharField(max_length=100)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='imp_location_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Name', models.CharField(max_length=100)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('Pin', models.BigIntegerField()),
                ('Dob', models.DateField()),
                ('Phone', models.BigIntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('Photo', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAFE_DRIVE_APP.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='pothole_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAFE_DRIVE_APP.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='location_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAFE_DRIVE_APP.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Feedback', models.CharField(max_length=100)),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAFE_DRIVE_APP.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('complaint', models.CharField(max_length=100)),
                ('Reply', models.CharField(max_length=100)),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAFE_DRIVE_APP.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='ambulance_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('Pin', models.BigIntegerField()),
                ('Dob', models.DateField()),
                ('Phone', models.BigIntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('Photo', models.FileField(upload_to='')),
                ('Id_proof', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAFE_DRIVE_APP.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='accident_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Status', models.CharField(max_length=100)),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAFE_DRIVE_APP.user_table')),
            ],
        ),
    ]
