# Generated by Django 3.2.24 on 2024-03-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAFE_DRIVE_APP', '0002_auto_20240301_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='imp_location_table',
            name='photo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
