# Generated by Django 3.2.24 on 2024-03-30 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAFE_DRIVE_APP', '0003_imp_location_table_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident_table',
            name='AMBULANCE_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SAFE_DRIVE_APP.ambulance_table'),
            preserve_default=False,
        ),
    ]
