# Generated by Django 3.2.24 on 2024-03-30 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAFE_DRIVE_APP', '0004_accident_table_ambulance_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident_table',
            name='AMBULANCE_ID',
        ),
        migrations.AddField(
            model_name='accident_table',
            name='AMBULANCE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SAFE_DRIVE_APP.ambulance_table'),
        ),
    ]
